pring:
  main:
    allow-circular-references: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:knots-demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 20
  application:
    name: whistle-example-producer

logging:
  level:
    org.coderclan: trace

server:
  port: 0
